# Generated by Django 2.2.8 on 2020-03-08 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MASTERCARD'), ('AMEX', 'AMEX')], max_length=10)),
                ('isDefault', models.BooleanField()),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exampleapp.Customer')),
            ],
            options={
                'unique_together': {('uid', 'cardNumber')},
            },
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='colour',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='sid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='style',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('address', models.TextField()),
                ('payMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exampleapp.PaymentMethod')),
                ('sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exampleapp.Shoe')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exampleapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exampleapp.Shoe')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exampleapp.Customer')),
            ],
            options={
                'unique_together': {('uid', 'sid')},
            },
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('isDefault', models.BooleanField()),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exampleapp.Customer')),
            ],
            options={
                'unique_together': {('uid', 'address')},
            },
        ),
    ]
