# Generated by Django 2.2.8 on 2020-04-13 20:35

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0004_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
